#!/bin/sh

###
# Configure SSH keys prior to executing this script.
##
# Usage: getdata -r remote_system -i interval -c count
###

OPTIND=1
RemoteSystem=""
RemoteUser="root"
Interval=300
Count=1

while getopts "h?r:i:c:u:" opt; do
  case "$opt" in
    h|\?)
      echo "usage: getdata -r remote_system [-i interval] [-c count]"
      exit 0
      ;;
    r)
      RemoteSystem=${OPTARG}
      ;;
		u)
			RemoteUser=${OPTARG}
			;;
    i)
      Interval=${OPTARG}
      ;;
    c)
      Count=${OPTARG}
      ;;
  esac
done

scp ${RemoteUser}@${RemoteSystem}:/var/www/miq/vmdb/VERSION .
ssh ${RemoteUser}@${RemoteSystem} uptime >uptime.txt
ssh ${RemoteUser}@${RemoteSystem} ps auxf >ps-start.txt

scp ~/bin/smem ~/bin/capture_smem ~/bin/swapusage ${RemoteUser}@${RemoteSystem}:
while true
do
	T=`date +%C%y%m%d_%H%M%S`
  echo -e "Capturing Quantum: ${T}\c"
	ssh ${RemoteUser}@${RemoteSystem} ./capture_smem >smem.${T}
	ssh ${RemoteUser}@${RemoteSystem} ./swapusage >swapusage.${T}
  echo ", complete"

  Count=$((Count - 1))
  if [ ${Count} -eq 0 ]
  then
		ssh ${RemoteUser}@${RemoteSystem} "rm capture_smem swapusage"
    ssh ${RemoteUser}@${RemoteSystem} ps auxf >ps-end.txt
    exit 0
  else
    sleep ${Interval}
  fi
done
