#!/bin/sh

###
# TODO:
#       1) Add option for specifying where the generated report is to be created
#       2) Add option to specify the name of the generated report
###

###
# Source Data File Format:
#
#     NAME, PID, PSS, RSS, USS, VSS, SWAP
#
# Which is the output format of the get_smem data collection tool. Typically
# we run get_smem on a system to capture the smem(1) data for later
# analysis, typically via per_worker_pss.
###

rm -f pss.csv
rm -f /tmp/process_names_pids.txt

###
# Get list of Process Names and PIDs
###
cat smem.201* | grep -v "NAME, PID" | cut -d',' -f1,2 | sort -k2 -t"," | uniq | sort -f | sed 's/,//' > /tmp/process_names_pids.txt

###
# Build the CSV file header rows:
#
# Row 1: Process Names
# Row 2: Process PID
###
echo "Date, Time,\c" >pss.csv
cat /tmp/process_names_pids.txt | while read N P
do
  ShortName=`echo ${N} | sed -e 's/InfraManager:://' -e 's/Openstack::NetworkManager/OSNM/' -e 's/Openstack::CloudManager/OSCM/' -e 's/StorageManager::CinderManager/SMCM/' -e 's/StorageManager::SwiftManager/SMSM/'`
  echo "${ShortName}-${P},\c" >>pss.csv
done
echo "" >>pss.csv

###
# For each time quantums add a row which contains the PSS value for each process which was
# active in that time period.
###
ls smem* | cut -d'.' -f2 | cut -d' ' -f1 | while read T
do
  echo "${T}"
  TIME=`echo ${T} | cut -d'_' -f2`
  HOUR=`echo ${TIME} | cut -c1-2`
  MINUTE=`echo ${TIME} | cut -c3-4`
  SECOND=`echo ${TIME} | cut -c5-6`
  DATE=`echo ${T} | cut -d'_' -f1`
  YEAR=`echo ${DATE} | cut -c1-4`
  MONTH=`echo ${DATE} | cut -c5-6`
  DAY=`echo ${DATE} | cut -c7-8`

  echo "${YEAR}/${MONTH}/${DAY},${HOUR}:${MINUTE}:${SECOND},\c" >>pss.csv
  cat /tmp/process_names_pids.txt | while read N P
  do
    PSS=`grep " ${P}," smem.${T} | sed -e 's/ *//' | cut -d',' -f3`
    echo "${PSS},\c" >>pss.csv
  done
  echo "" >>pss.csv

done

rm /tmp/process_names_pids.txt

exit 0
