#!/bin/sh

if [ $# -ne 1 ]
then
  echo "usage: $0 file_name"
  exit 0
fi

echo "Recursively remove [${1}] (y/n)?"
read Continue

if [ " ${Continue}" != " y" ]
then
  exit 1
fi

find . -name "${1}" -print | while read D
do
	rm "${D}"
done
